apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-assistant-config
  labels:
    app: ops-incident-assistant
data:
  openai-base-url: "https://your-openai-compatible-endpoint.com/v1"
  mcp-server-url: "https://mcp-server-aap.apps.cluster-5ffmt.5ffmt.sandbox1919.opentlc.com/mcp"
  model-name: "DeepSeek-R1-Distill-Qwen-14B-W4A16"
  webhook-path: "7d1a79c6-2189-47d5-92c6-dfbac5b1fa59"


