apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/jwerak/agent-ops-assistant/k8s

# Add any customizations here, for example:
# namespace: aiops
# patches:
#   - path: patch-configmap.yaml
#   - path: patch-secret.yaml
