apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aiops

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app: ops-incident-assistant
  component: aiops


