apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-server-aap

resources:
  - https://github.com/jwerak/mcp-server-aap/k8s/base
  - secret.yaml
  - namespace.yaml

# Add any customizations here, for example:
# namespace: aiops
patches:
  - path: patch-configmap.yaml
